name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  build:
    # TODO: it might be worth it to split these into different jobs so that they can run in parallel
    name: Build things
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Make result directory
        run: mkdir result

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Install dependencies for subdivision tool
        working-directory: subdivision
        run: npm i

      - name: Build subdivision tool
        working-directory: subdivision
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build

      - name: Make result subdirectory for subdivision tool
        run: mkdir result/subdivision

      - name: Copy subdivision tool to result directory
        run: cp subdivision/build/* result/subdivision/ -r

      - name: Copy main page to result directory
        run: cp main_page/* result/ -r

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'result/'

  deploy:
    name: Deploy site
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deploymnet
        uses: actions/deploy-pages@v5
